In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

# Task 1 — Clean the Data

In [2]:
df.describe()

       customer_id        age  annual_income
count     6.000000   3.000000       6.000000
mean      2.833333  33.333333   79166.666667
std       1.471960   7.637626   27643.564652
min       1.000000  25.000000   40000.000000
25%       2.000000  30.000000   65000.000000
50%       2.500000  35.000000   80000.000000
75%       3.750000  37.500000   91250.000000
max       5.000000  40.000000  120000.000000

## Impute missing values in age with the median and in city with the mode

In [3]:
df['age'] = df['age'].fillna(df['age'].median())
df['city'] = df['city'].fillna(df['city'].mode()[0])

df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0   Delhi    Male          95000

# Task 2 — Encode Categorical Columns

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
print(df.columns)

Index(['customer_id', 'age', 'city', 'gender', 'annual_income'], dtype='object')

## Apply One-Hot Encoding to city

In [8]:
if 'city' in df.columns:
    df = pd.get_dummies(df, columns=['city'], prefix='city')
df

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0    Male          40000       False         True
1            2  35.0  Female          80000        True        False
2            3  35.0  Female          60000        True        False
3            4  35.0    Male         120000       False         True
4            2  35.0  Female          80000        True        False
5            5  40.0    Male          95000        True        False

## Apply Label Encoding to gender

In [9]:
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

print("Encoded DataFrame:\n", df)

Encoded DataFrame:
    customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000       False         True
1            2  35.0       0          80000        True        False
2            3  35.0       0          60000        True        False
3            4  35.0       1         120000       False         True
4            2  35.0       0          80000        True        False
5            5  40.0       1          95000        True        False

# Task 3 — Scale Numerical Features

### Min-Max Scaling (using MinMaxScaler)
### Standardisation (using StandardScaler)

In [12]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler_minmax = MinMaxScaler()
scaler_standard = StandardScaler()

df_minmax = df.copy()
df_minmax[['age', 'annual_income']] = scaler_minmax.fit_transform(df_minmax[['age', 'annual_income']])

df_standard = df.copy()
df_standard[['age', 'annual_income']] = scaler_standard.fit_transform(df_standard[['age', 'annual_income']])

print("\nMin-Max Scaled DataFrame:\n", df_minmax)
print("\nStandardised DataFrame:\n", df_standard)

Min-Max Scaled DataFrame:
    customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1  0.000000       1         0.0000       False         True
1            2  0.666667       0         0.5000        True        False
2            3  0.666667       0         0.2500        True        False
3            4  0.666667       1         1.0000       False         True
4            2  0.666667       0         0.5000        True        False
5            5  1.000000       1         0.6875        True        False

Standardised DataFrame:
    customer_id       age  gender  annual_income  city_Delhi  city_Mumbai
0            1 -2.042649       1      -1.552077       False         True
1            2  0.185695       0       0.033023        True        False
2            3  0.185695       0      -0.759527        True        False
3            4  0.185695       1       1.618123       False         True
4            2  0.185695       0       0.033023        True        False
5            5  1.299867       1       0.627435        True        False

### **Min‑Max Scaling:** rescales values into a fixed range [0,1]. Useful when you want bounded features (e.g., neural networks).

### **Standardisation:** centers data to mean 0, variance 1. Better when features follow a Gaussian distribution or when outliers exist.